### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by psiphi75**

### CODE REVIEW

**Comment by psiphi75** [comment]
This needs further investigation.

**Comment by wilberforce** [comment]
I think you are correct - you do need to be one level up before...

**Comment by psiphi75** [comment]
Yes, but the following instructions do that anyway.  I hope to complete the instructions and create one Pull Request.

**Comment by wilberforce** [comment]
and I have since found replacing both makes with
`make -j 4`

Speeds up the build considerably

**Comment by wilberforce** [comment]
The reason behind this stuff was to get repeatably, and then bring the code into the travis build for the espruino core
Ideally want the esp-idf stuff to build all the library files, rather than have a target of a .bin file that never gets used!

**Comment by psiphi75** [comment]
When I run `git submodule update --init` in the `espruini-esp` folder I get the following message:

```Text
Submodule 'esp-idf' (https://github.com/espressif/esp-idf.git) registered for path 'esp-idf'
Cloning into '/home/simon/Projects/JuceBox/esp32/espruino-esp32/esp-idf'...
error: no such remote ref d5bd5142243926ef7edb34ea9a21de495f90dd42
Fetched in submodule path 'esp-idf', but it did not contain d5bd5142243926ef7edb34ea9a21de495f90dd42. Direct fetching of that commit failed.
```

Any ideas?

**Comment by wilberforce** [comment]
I think the link to the submodule is pointing to an out of date link.
The submodule would need to be dropped and re-added I think

root@OFFICE-PC:~/esp32/espruino-esp32# git submodule status
+c61fdff7293c68142d052376eace1a3a9f6a2312 esp-idf (v2.0-rc1-30-gc61fdff)

It looks like this is out of date.

This stuff is moving goal posts, as the esp-idf is quite fluid!

It's means to be tied to here:

https://github.com/espressif/esp-idf/tree/v2.0-rc1

**Comment by wilberforce** [comment]
Ok - do a pull from https://github.com/wilberforce/espruino-esp32 again....

the esp-idf is now pointing to a valid tree..


I fixed with:

in:
/esp32/espruino-esp32

```
git rm --cached esp-idf
git submodule update --init
```

and pushed with:
```
git add esp-idf
git commit -m "update esp-idf submodule"
git push
```

**Pull request closed without merging**
